### ISSUE TITLE
Add profile, module, application model

### ISSUE THREAD

**Issue by jbonofre** [jbonofre/karaf5#6]
The main `KarafConfig` (populated via `karaf.json` or programmatically) should describe a multi layer model:

* spec only load specification (no implement) in the "main/system" classloader (shared by all applications and Karaf itself)
* profile is a classloader populated with a set of jar
* a module is an application (spring boot, microprofile, osgi bundle) with its own classloader. It can optionally use a profile classloader
* an application (previously extension) is a group of module (just a convenient way to install a set of modules)

**Comment by jbonofre** [comment]
I think that profile (classloader), module (bundle) and application (previously extension) make sense. Not sure about spec. 

@fpapon thoughts ?

**Comment by jbonofre** [comment]
@fpapon my proposal is: stack (classloader), module (bundle), profile (group of bundles). Thoughts ?

**Comment by fpapon** [comment]
+1 make sense, we can add specs in library for example

**Comment by jbonofre** [comment]
Completely refactore to use SPI and new wording.
